swagger: "2.0"

info:
  version: 1.0.0
  title: repos-researcher

paths:
  /search/account:
    get:
      description: GitHubアカウントの検索を行う<br>
        ・https://docs.github.com/ja/rest/search#search-users<br>
        ・https://docs.github.com/ja/rest/users/users#get-a-user
      parameters:
        - name: user
          in: query
          description: ユーザー名
          required: false
          type: string
        - name: max-followers
          in: query
          description: 最高のフォロワー数
          required: false
          type: integer
        - name: min-followers
          in: query
          description: 最低のフォロワー数
          required: false
          type: integer
        - name: language
          in: query
          description: 指定の言語のリポジトリを有するアカウント
          required: false
          type: integer
        - name: repos
          in: query
          description: ユーザーが所有するリポジトリの数
          required: false
          type: integer
        - name: location
          in: query
          description: プロフィールに表示されている国
          required: false
          type: integer
        - name: sort
          in: query
          description: ソート（降順）
          required: false
          type: integer

      responses:
        200:
          description: Successful responses
          schema:
            type: array
            items:
              type: object
              properties:
                login:
                  type: string
                  example: konan0802
                name:
                  type: string
                  example: Konan
                avatar_url:
                  type: string
                  example: https://avatars.githubusercontent.com/u/46038618?v=4
                company:
                  type: string
                  example: null
                location:
                  type: string
                  example: Tokyo
                twname:
                  type: string
                  example: null
                repos:
                  type: integer
                  example: 17
                gists:
                  type: integer
                  example: 1
                followers:
                  type: integer
                  example: 0
                following:
                  type: integer
                  example: 0
                created_at:
                  type: string
                  example: 2018-12-21T02:26:31Z
                updated_at:
                  type: string
                  example: 2022-05-08T06:19:26Z
        304:
          description: Not modified
        422:
          description: Validation failed
        503:
          description: Service unavailable

  /search/repository:
    get:
      description: |
        GitHubリポジトリの検索を行う<br>・https://docs.github.com/ja/rest/search#search-repositories

      parameters:

      responses:
        200:
          description: Successful responses
          schema:
            title: ArrayOfPosts
            type: array
            items:
              title: Posts
              type: object
              properties:
                name:
                  type: string
                title:
                  type: string
                published:
                  type: boolean
                content:
                  type: string
        304:
          description: Not modified
        422:
          description: Validation failed
        503:
          description: Service unavailable

  /save/account:
    post:
      description: |
        GitHubアカウントの保存を行う

      parameters:

      responses:
        200:
          description: Successful responses
          schema:
            title: ArrayOfPosts
            type: array
            items:
              title: Posts
              type: object
              properties:
                name:
                  type: string
                title:
                  type: string
                published:
                  type: boolean
                content:
                  type: string

  /save/repository:
    post:
      description: |
        GitHubリポジトリの保存を行う

      parameters:

      responses:
        200:
          description: Successful responses
          schema:
            title: ArrayOfPosts
            type: array
            items:
              title: Posts
              type: object
              properties:
                name:
                  type: string
                title:
                  type: string
                published:
                  type: boolean
                content:
                  type: string

  /fettch/savedaccount:
    get:
      description: |
        保存したGitHubアカウントを取得する

      parameters:

      responses:
        200:
          description: Successful responses
          schema:
            title: ArrayOfPosts
            type: array
            items:
              title: Posts
              type: object
              properties:
                name:
                  type: string
                title:
                  type: string
                published:
                  type: boolean
                content:
                  type: string

  /fettch/savedrepository:
    get:
      description: |
        保存したGitHubリポジトリを取得する

      parameters:

      responses:
        200:
          description: Successful responses
          schema:
            title: ArrayOfPosts
            type: array
            items:
              title: Posts
              type: object
              properties:
                name:
                  type: string
                title:
                  type: string
                published:
                  type: boolean
                content:
                  type: string

  /delete/savedaccount:
    delete:
      description: |
        保存したGitHubアカウントを取得する

      parameters:

      responses:
        200:
          description: Successful responses
          schema:
            title: ArrayOfPosts
            type: array
            items:
              title: Posts
              type: object
              properties:
                name:
                  type: string
                title:
                  type: string
                published:
                  type: boolean
                content:
                  type: string

  /delete/savedrepository:
    delete:
      description: |
        保存したGitHubリポジトリを取得する

      parameters:

      responses:
        200:
          description: Successful responses
          schema:
            title: ArrayOfPosts
            type: array
            items:
              title: Posts
              type: object
              properties:
                name:
                  type: string
                title:
                  type: string
                published:
                  type: boolean
                content:
                  type: string
