name: Deploy container image to AWS Lambda（prd）
on:
  push:
    branches:
      - main
env:
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ROLE_NAME: ${{ secrets.AWS_ROLE_NAME }}
  AWS_ROLE_SESSION_NAME: ${{ secrets.AWS_ROLE_SESSION_NAME }}
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY: repos-researcher
  LAMBDA_FUNCTION_NAME: repos-researcher

permissions:
  id-token: write
  contents: read
jobs:
  aws-deploy:
    name: Push to ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_NAME }}
          role-session-name: ${{ env.AWS_ROLE_SESSION_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get current date and time
        env:
          TZ: "Asia/Tokyo"
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d-%H:%M')"

      - name: Lambda publish version
        id: publish-version
        run: |
          echo "::set-output name=version::$(aws lambda publish-version --function-name $LAMBDA_FUNCTION_NAME --description ${{ steps.date.outputs.date }})"

      - name: Lambda update alias
        id: update-alias
        run: |
          run: echo ${{ steps.publish-version.outputs.version }}
